const ACTION_TYPES = {
  SET_USER: "SET_USER",
  CREATE_ROOM: "CREATE_ROOM",
  MODIFY_ROOM_SUCCES: "MODIFY_ROOM_SUCCES",
  MODIFY_ROOM_FAILURE:"MODIFY_ROOM_FAILURE",
  DELETE_ROOM_SUCCES: "DELETE_ROOM_SUCCES",
  DELETE_ROOM_FAILURE:"DELETE_ROOM_FAILURE",
  SELECT_ROOM:"SELECT_ROOM",
  ERROR:"ERROR"
}
    
export default ACTION_TYPES;