const ACTION_TYPES = {
  SET_USER: "SET_USER",
  SET_USER_UID:"SET_USER_UID",
  GET_USER_ROOMS: "GET_USER_ROOMS",
  GET_MESSAGES_ROOM: "GET_MESSAGES_ROOM",
  MODIFY_ROOM_SUCCES: "MODIFY_ROOM_SUCCES",
  MODIFY_ROOM_FAILURE:"MODIFY_ROOM_FAILURE",
  DELETE_ROOM_SUCCES: "DELETE_ROOM_SUCCES",
  DELETE_ROOM_FAILURE:"DELETE_ROOM_FAILURE",
  SELECT_ROOM:"SELECT_ROOM",
  ERROR:"ERROR"
}
    
export default ACTION_TYPES;