const ACTION_TYPES = {
  SET_USER: "SET_USER",
  CREATE_ROOM: "CREATE_ROOM",
  DELETE_ROOM: "DELETE_ROOM",
  DELETE_ROOM_FAILURE:"DELETE_ROOM_FAILURE",
  SELECT_ROOM:"SELECT_ROOM",
  ERROR:"ERROR"
}
    
export default ACTION_TYPES;